trigger:
- master

pool:
  name: 'Default'  # Nombre del pool con tu agente autoalojado

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'